import type { Metadata } from 'next';
import { Poppins, Red_Hat_Mono } from 'next/font/google';
import { QueryProvider } from '@/components/QueryProvider';
import './globals.css';
import { Footer } from '@/components/layout/Footer';
import { Navbar } from '@/components/layout/Navbar';

const redHatMono = Red_Hat_Mono({
  variable: '--font-red-hat-mono',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'DataViz — University Data Explorer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${redHatMono.variable} font-[family-name:var(--font-poppins)] flex min-h-screen flex-col antialiased`}
      >
        <Navbar />
        <main className="flex-1">
          <QueryProvider>{children}</QueryProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
