/* eslint-disable */
// This file is auto-generated by scripts/generate-article-registry.mjs.
// Do not edit manually.

import { ArticleMeta as ArticleMeta0 } from './admission-massachusetts-private/content';
import { ArticleMeta as ArticleMeta1 } from './admissions-top-20/content';
import { ArticleMeta as ArticleMeta2 } from './financial-aid-top-20/content';

export const articleRegistry = [
  { slug: 'admission-massachusetts-private', ArticleMeta: ArticleMeta0 },
  { slug: 'admissions-top-20', ArticleMeta: ArticleMeta1 },
  { slug: 'financial-aid-top-20', ArticleMeta: ArticleMeta2 },
];
