/* eslint-disable */
// This file is auto-generated by scripts/generate-article-registry.mjs.
// Do not edit manually.

import type { ArticleMeta as ArticleMetaType } from '@/components/article/types';
import * as _Article0 from './acceptance-rates-jesuit-schools-2022-2024/article.mdx';
import * as _Article1 from './admission-massachusetts-private/article.mdx';
import * as _Article2 from './financial-aid-top-20/article.mdx';
import * as _Article3 from './sat-act-percentiles-jesuit-schools-2022-2024/article.mdx';
import * as _Article4 from './uc-2024-cost-of-attendance/article.mdx';
const ArticleMeta0 = (_Article0 as unknown as { ArticleMeta: ArticleMetaType }).ArticleMeta;
const ArticleMeta1 = (_Article1 as unknown as { ArticleMeta: ArticleMetaType }).ArticleMeta;
const ArticleMeta2 = (_Article2 as unknown as { ArticleMeta: ArticleMetaType }).ArticleMeta;
const ArticleMeta3 = (_Article3 as unknown as { ArticleMeta: ArticleMetaType }).ArticleMeta;
const ArticleMeta4 = (_Article4 as unknown as { ArticleMeta: ArticleMetaType }).ArticleMeta;

export const articleRegistry = [
  { slug: 'acceptance-rates-jesuit-schools-2022-2024', ArticleMeta: ArticleMeta0 },
  { slug: 'admission-massachusetts-private', ArticleMeta: ArticleMeta1 },
  { slug: 'financial-aid-top-20', ArticleMeta: ArticleMeta2 },
  { slug: 'sat-act-percentiles-jesuit-schools-2022-2024', ArticleMeta: ArticleMeta3 },
  { slug: 'uc-2024-cost-of-attendance', ArticleMeta: ArticleMeta4 },
];
